---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list: 
      - recipe[consul-kio::server]
      - recipe[haproxy-kio::default]
    attributes:
