source "https://supermarket.chef.io"

metadata

cookbook 'haproxy', '~> 0.1', github: "gotchef/haproxy"
cookbook 'consul-kio', '~> 0.1.1', github: "kraveio/chef", rel: "consul-kio"

# temp, bug fix
cookbook 'consul-template', github: "franklinwise/chef-consul-template", branch: "config-dir-patch"
# cookbook 'consul-template', '~> 0.7.0'

