name             'consul-kio'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures consul-kio'
long_description 'Installs/Configures consul-kio'
version          '0.1.0'

depends 'consul'
depends 'aws-util'
